### ISSUE TITLE
Investigate servo open loop mode

### ISSUE THREAD

**Issue by henningkayser** [PickNikRobotics/UR10e_welding_demo#17]

**Comment by AdamPettinger** [comment]
I tested this a little bit last week, see [my initial work here](https://github.com/AdamPettinger/moveit2/tree/open_loop_servo_mode). This made our UR5e jog smoother but still not perfect

After discussion with @nbbrooks, we think the correct solution is to finish porting the UR velocity hardware interface and to use velocity controllers instead of position controllers. He was going to follow up and get an ETA on that

In the mean time, the linked branch was working on our hardware for smoother motion
