### ISSUE TITLE
Copy moveit_config from UR ROS2 driver package

### ISSUE THREAD

**Issue by henningkayser** [PickNikRobotics/UR10e_welding_demo#3]
https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver

**Comment by AdamPettinger** [comment]
> https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver

In that repo, they have example launch files for launching with ROS 2 Control, as well as MoveIt 2. I just pulled and tested with UR10e, and everything looked good (MoveIt, fake controller, Rviz).

Given that eventually we will want the hardware drivers, I am thinking instead of copying the `moveit_config` and `ur_description` packages here, we should just clone the Universal Robots repo (and it's depends) and use the pre-made launch files. Thoughts? @henningkayser

**Comment by henningkayser** [comment]
Yes, that makes a lot of sense. We probably still want a separate moveit config package that launches the custom description and includes more planner settings, if any.
